spring:
  cloud:
    config:
      import-check:
        enabled: false
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect
  main:
    web-application-type: servlet

server:
  port: ${app.container.port:8080}

eureka:
  instance:
    hostname: ${eureka.instance.hostname:demo.application}
    preferIpAddress: ${eureka.instance.preferIpAddress:true}
  client:
    registerWithEureka: ${eureka.client.register-with-eureka:true}
    fetchRegistry: ${eureka.client.fetch-registry:true}
    serviceUrl:
      defaultZone: ${eureka.client.service-url.defaultZone:http://eureka.eureka:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,configprops,loggers,heapdump,threaddump
  endpoint:
    health:
      show-details: always
      show-components: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: demo
    distribution:
      percentiles:
        http.server.requests: 0.5,0.9,0.95,0.99
        method.timed: 0.5,0.9,0.95,0.99
      slo:
        http.server.requests: 10ms,50ms,100ms,200ms,500ms,1s,2s,5s,10s
        method.timed: 10ms,50ms,100ms,200ms,500ms,1s,2s,5s,10s
  info:
    build:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: info
    com.example: debug
    org.springframework.web.servlet.DispatcherServlet: debug
    oracle.ucp: debug
    com.oracle.microtx: debug
  pattern:
    level: "%5p [demo,%X{traceId:-},%X{spanId:-}]"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html