spec:
  template:
    spec:
      containers:
      - name: demo
        imagePullPolicy: Always
        command: ["java"]
        args: ["-jar", "/deployments/demo-0.0.1-SNAPSHOT.jar"]
        env:
        - name: MP_LRA_COORDINATOR_URL
          value: http://otmm-tcs.otmm.svc.cluster.local:9000/api/v1/lra-coordinator
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
          value: "true"
        - name: EUREKA_CLIENT_FETCH_REGISTRY
          value: "true"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: http://eureka.eureka:8761/eureka
        - name: CONFIG_SERVER_URL
          value: http://config-server.config-server.svc.cluster.local:8080
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://signoz-otel-collector.observability:4318
        - name: APP_CONTAINER_PORT
          value: "8080"
        - name: SPRING_PROFILES_ACTIVE
          value: obaas
        - name: SPRING_CONFIG_LABEL
          value: 0.0.1
        - name: EUREKA_INSTANCE_HOSTNAME
          value: demo.application
        - name: MP_LRA_PARTICIPANT_URL
          value: http://demo.application.svc.cluster.local:8080
        - name: LIQUIBASE_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: admin-liquibasedb-secrets
              key: db.username
        - name: LIQUIBASE_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: admin-liquibasedb-secrets
              key: db.password
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: customer-db-secrets
              key: db.username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: customer-db-secrets
              key: db.password
        - name: DB_SERVICE
          valueFrom:
            secretKeyRef:
              name: customer-db-secrets
              key: db.service
        - name: SPRING_DATASOURCE_URL
          value: jdbc:oracle:thin:@$(DB_SERVICE)?TNS_ADMIN=/oracle/tnsadmin
        - name: CONNECT_STRING
          value: jdbc:oracle:thin:@$(DB_SERVICE)?TNS_ADMIN=/oracle/tnsadmin
        volumeMounts:
        - name: obaas-adb-tns-admin-1
          mountPath: /oracle/tnsadmin
      volumes:
      - name: obaas-adb-tns-admin-1
        secret:
          secretName: obaas-adb-tns-admin-1